### PR TITLE
Feature/authentication

### PR DESCRIPTION
**Pull request by JoannaLapa**
- useAuth hook created;
- Root page created as a main page before authorization; 
- firebase unworking data .env fixed;
- AuthProvider created in the folder providers;
- props title added to GoBack component for better reusability;
- Routes corrected in index.js and sensitive data protected with ProtectedRoute.

### CODE REVIEW

**Comment by k-stopczynska** [comment]
So I pulled the changes and still have a problem with process.env variables, it workes with hard coded data though.

You are using AuthProvider.js which is a context, but we actually use Redux for state and it would be cleaner solution to use only one state manager, then you can all the login for signingIn and Out move to hook, it would be more readable.

I think it would be a better UX to navigate logged in user already to invoices and not displaying this Go to invoices button.

**Comment by JoannaLapa** [comment]
> 
Thank you Klaudia for your review. 
I replaced AuthProvider with the useAuth hook. 
I also added authSlice for the isLoggedIn state. 
I set auto-navigate to invoices when the user is logged in. 
If you would have a while check please again if i can merge the branch.

**Comment by k-stopczynska** [comment]
Asia, great job on learning Redux:) Works smoothly now!

Just two quick questions: 
1. Why do we need logIn and logOut status? I think user status alone would suffice. Then you dispatch only one action in every scenario in useAuth.
2. I don't think we ever reuse authResult variable from useAuth so we can just call this firebase function signInWithPopUp and not store it
Just a remark: only state is mandatory in reducers, if you don't use action, you can omit it:)

Overall- great job!

**Comment by JoannaLapa** [comment]
You're right Klaudia, it's not necessary to use 2 states, user state would be enough. 

I fixed all cases: 

- isLoggedIn state has been deleted and I use everywhere user state. 
- The AuthResult variable has been deleted.
- Actions as parameters have been deleted where unused.

**Comment by k-stopczynska** [comment]
Looks good, ready to merge:)

**Pull request merged**
