### PR TITLE
Feature/edit invoice

### PR DESCRIPTION
**Pull request by k-stopczynska**
- edit invoice form added
- changed file and components names
- added hooks for errors and rendering list of items
- moved changeDateFormat function to utils since it was used twice
- fixed total sum for invoice
- fixed zip codes just to match numbers and letters from 2 to 10 signs and a white space

### CODE REVIEW

**Comment by pizgo** [comment]
couple of issues that can be addressed:
1) validation: I would change the errors .max in description, street address, city and country (eg. United Kingdom is already too long and form throws error)
2) button to toggle the status (mark as paid/unpaid) is not working (HeaderInvoiceView)
3) bug:  When I try to save as draft it works for the first time. If I want to repeat this, there is an error: cannot assign to read only property 'status' of object '#<Object>'; TypeError: Cannot assign to read only property 'status' of object '#<Object>'

styling issues:
- cursor changes to pointer after hovering the text area and I find it annoying from the ux perspective. Would change it to normal cursor

Random thoughts:
- I would render only one field for providing new item (now there are two of them and I think it’s counter intuitive)
- I think we should consider creating one separate form component and then reuse it in both newInvoice and editInvoice (since we double the form code twice)
- I’ve noticed you’ve been using nested ternary operators a lot - I think it would be good to write it as a regular if statement, for better readability

**Comment by k-stopczynska** [comment]
1. validation: **done**
2. button to toggle the status - Ewelina was supposed to do that as I remember
3. bug: When I try to save as draft it works for the first time. If I want to repeat this, there is an error: cannot assign to read only property 'status' of object '#'; TypeError: Cannot assign to read only property 'status' of object '#'- I ultimately was able to recreate this, but I need more time to figure out what is going on
4. cursor changes to pointer after hovering the text area - it's in design, I'll take it to **backlog** to talk about
5. I would render only one field for providing new item- also in design, goes to **backlog**
6. I think we should consider creating one separate form component and then reuse it in both newInvoice and editInvoice (since we double the form code twice)- **done**, very good point, I was too tired to see it then:)
7. I’ve noticed you’ve been using nested ternary operators a lot - I think it would be good to write it as a regular if statement, for better readability- you will have to point me out the place where I should change this, bc I spotted this only in rendering List Items- and sure, it would improve readability, but if we go with rendering only one item- the problem will disappear. So, if there is any more places like this- let me know. If this is the place, I would wait for decision on what to do with this component, ok?

**Comment by pizgo** [comment]
button to toggle the status - Ewelina was supposed to do that as I remember - sorry, I lost it 

ternary operators - they are also in the Input component. Maybe it's not like there is tons of them, but it just caught my eye :) 

design issues - as we discussed it on today's call, we decided to change it in accordance to the suggestions from my previous comment :)

**Review by pizgo — APPROVED** [review]
There are still some small issues regarding the design:
1. modal with new invoice form on desktop view is behaving differently than modal with edit invoice: when scrolling down, the invoice list behind the modal is being scrolled, not the content in the modal. I would make modal scrollable and fitted to the screen with height 
2. on the md breakpoint the div with buttons is at the bottom of the page and there is a huge space between it and the rest of the form 
3. go back button is splittet (arrow at the start, "go back" at the end) (it looks ok on the edit form modal)
4. Edit form modal - for the sake of consitency I would make the buttons centered on the sm view

BUT i think we can merge this branch to develop and let us all work on the updated version. Those issues are not so important regarding whole app and can be fixed as a new tasks

**Pull request merged**
